### ISSUE TITLE
User Model.

### ISSUE THREAD

**Issue by earvingemenez** [Swiftkind/portal#3]
Assignee: Micheal

fields:
- email
- first_name
- last_name
- is_active
- is_staff
- is_superuser

Acceptance Criteria:
- Extend the default User model to a custom model named `User` so we can fully customized it. Set `email` as the username and remove the existence of the `username` field.
- createsuperuser command should still work with email as the primary credentials. Include the first and last name as required fields.
- unit test at users/tests/models_test.py

**Comment by mich71095** [comment]
@earvingemenez  
 - Add "users" app and extend the default User model. https://github.com/Swiftkind/portal/pull/8
